### ISSUE TITLE
mlp.py: add multiprocessing.Pool() to speed up the MLP calculation

### ISSUE THREAD

**Issue by 3fon3fonov** [mzechmeister/python#11]
It will be much faster to calculate the MPL power if you do it using several threads/processes.

Please see how this is done in the [transitleastsquares](https://github.com/hippke/tls).

**Comment by 3fon3fonov** [comment]
For some reason, I cannot push a pull request (no time to investigate), but I included multiprocess option in mlp.py. I will send it to you by e-mail.

In the Exo-Striker GUI looks like this:

![mlp_ncpus_example](https://user-images.githubusercontent.com/44244057/129750993-d4d3d1ed-3d94-4ccd-a13e-8f63b7505a85.png)

I also attach the code, please fell free to clean some of my mess. 

You will have to add the "pathos" dependency in mlp.py. Else, I guess this can also be done with the intrinsic "multiprocessing", but I would highly recommend to use Pathos, because it can pickle almost every class and function.

**Comment by mzechmeister** [comment]
Why did you changed the index from `k` (best freqency) to `0` (f=0) in
https://github.com/mzechmeister/python/blob/89a80962986352a320cf70e87275b8edae5c3002/mlp.py#L420
vs.
https://github.com/mzechmeister/python/blob/fef62dcb3387f19fa095165bec47444598d14d0a/mlp.py#L448

**Comment by 3fon3fonov** [comment]
I was debugging and forgot to revert! Sorry!

**Comment by mzechmeister** [comment]
`mlp.py` is pretty much stand alone and I don't like to force a dependency on `pathos`. Thus the dependency should be optional. The import can done with `try`. `ncpus` can serve as switcher. It's default could be `None`; while `0,1, ...` could be used by `Pool`.

**Comment by 3fon3fonov** [comment]
This is perfectly fine! Will you push these changes?

**Comment by mzechmeister** [comment]
Check my changes in 9acfadb. I tested it with python2 and python3, but not for the `ncpus` option. (BTW, in this test python2 was faster (12.3 sec vs. 19.2 sec).

**Comment by 3fon3fonov** [comment]
Please comment pause(), because the use should not depend on it. Apart from that, all seems to work fine!

E.g. on my laptop with 4 physical CPUs (8 hyperthreaded cores), for a random RV dataset I get:

--- 8 CPUs done in 8.265009641647339 seconds --- 
--- 2 CPUs done in 14.07719898223877 seconds --- 
--- 1 CPUs done in 26.975532293319702 seconds --- 
--- 4 CPUs done in 7.923147916793823 seconds --- 

which is expected. 

Now we should add [progress bar](https://github.com/mzechmeister/python/issues/10)  and add flag for the [jitter](https://github.com/mzechmeister/python/issues/13) and the code is perfect!

**Comment by mzechmeister** [comment]
> Will you push these changes?

Done.
