### ISSUE TITLE
mlp.py -- AttributeError: 'numpy.ndarray' object has no attribute 'time'

### ISSUE THREAD

**Issue by 3fon3fonov** [mzechmeister/python#6]
File "./lib/mlp.py", line 160, in __init__
    self._assignTimeSeries(lc)
  File "./lib/mlp.py", line 203, in _assignTimeSeries
    t, y, e_y = lc.time, lc.flux, lc.error
AttributeError: 'numpy.ndarray' object has no attribute 'time'

I am trying to use it the same way as the gls.py, e.g.

#import gls as gls 
import mlp as gls

any recomendatios how to make it work, using the same API as in the gls.py?

**Comment by mzechmeister** [comment]
This refers to line 217 in
https://github.com/mzechmeister/python/blob/cb008faca08d44a0c5236de64971d8340591a5b6/mlp.py#L199-L217

While gls.py requires a tuple, mlp.py requires a list of tuple.
Passing only a tuple to mpl.py, can raise the error `object has no attribute 'time'`

**Comment by 3fon3fonov** [comment]
And what is your solution/suggestion?

what I usually do is, e.g.:

```
            RV_per = gls.Gls((fit.jd, fit.rvs, fit.rv_err), fast=True,  verbose=False)
```

jd,rvs, and rv_err are numpy arrays.

**Comment by mzechmeister** [comment]
The usage for one set is
```
RV_per = gls.Gls([(fit.jd, fit.rvs, fit.rv_err)], fast=True,  verbose=False)
```
and for two sets:
```
RV_per = gls.Gls([(harps.jd, harprs.rvs, harps.rv_err), (uves.jd, yves.rvs, uves,rv_err)], fast=True,  verbose=False)
```
So a list of tuples, i.e. you need additional brackets.

**Comment by 3fon3fonov** [comment]
Thanks, 

I see this is needed in mlp.py. Then for compatibility with gls.py, I would make the same in gls.py. I.e. to work with:

`  RV_per = gls.Gls([(fit.jd, fit.rvs, fit.rv_err)], fast=True,  verbose=False)`

and perhaps aslo with a tuple:

RV_per = gls.Gls((fit.jd, fit.rvs, fit.rv_err), fast=True,  verbose=False)
