### ISSUE TITLE
mlp.py -- norms = 'ZK' missing.

### ISSUE THREAD

**Issue by 3fon3fonov** [mzechmeister/python#7]
I understand that in mlp.py you may not be able to do ZK power. 

However, for consistency with the gls.py, please add it and do something like:

```

    def pnorm(self, norm="dlnL"):
        """
        Assign or modify normalization (can be done afterwards).
        Parameters
        ----------
        norm : string, optional
            The normalization to be used (default is 'lnL').
        Examples
        --------
        >>> gls.pnorm('wrms')
        """
        if norm == "ZK":
            norm ="dlnL"
            print("'ZK' normalization is not possible in Maximum Log-likelihood Periodogram, 'dlnL' normalisation was chosen instead ")
       ...
       ...
```

**Comment by mzechmeister** [comment]
I would keep only norms `dlnL`, `lnL`, `wrms`, `chisq` and remove `Scargle`, `HorneBaliunas`, `Cumming` and `ZK`.

Wrong input should should raise an error, rather than a "silent" fallback.

**Comment by 3fon3fonov** [comment]
In the ES, rising an error like this will crash the GUI. My suggestion above is not a silent fallback because it will warn the user that e.g. "ZK" is not available when mlp is used and will give something to work with. I can, of course, code this in my side, but it would be best if you provide some compatibility between the gls/mlp packages.

**Comment by mzechmeister** [comment]
Why do you call mlp with "ZK", if this option is not available?

**Comment by 3fon3fonov** [comment]
Because I can reuse all my GUI routines and only swap between gls and mlp. Otherwise, I have to add more logic what the GUI to show when gls is selected and when mlp. It is not a big deal, I can do it, but I was hoping for a 100 % compatibility.

**Comment by 3fon3fonov** [comment]
This is resolved, and not an issue anymore. Closing
