### ISSUE TITLE
mlp.py: TypeError: unsupported operand type(s) for +: 'map' and 'map'

### ISSUE THREAD

**Issue by 3fon3fonov** [mzechmeister/python#8]
I am passing a list of tuple, each element is a np.array

`            RV_per = mlp.Gls([(fit.fit_results.rv_model.jd, fit.fit_results.rv_model.rvs, fit.fit_results.rv_model.rv_err)], fast=True,  verbose=False, ofac=self.gls_ofac.value(), fbeg=omega[-1], fend=omega[0], norm='dlnL') `

Returns this:

 File "es_gui.py", line 2699, in mlp_search
    RV_per = mlp.Gls([(fit.fit_results.rv_model.jd, fit.fit_results.rv_model.rvs, fit.fit_results.rv_model.rv_err)], fast=True,  verbose=False, ofac=self.gls_ofac.value(), fbeg=omega[-1], fend=omega[0], norm='dlnL')
  File "./lib/mlp.py", line 162, in __init__
    self._calcPeriodogram()
  File "./lib/mlp.py", line 286, in _calcPeriodogram
    a0 = map(np.mean, self.y) + map(np.std, self.y)
TypeError: unsupported operand type(s) for +: 'map' and 'map'

**Comment by 3fon3fonov** [comment]
I am passing a list of tuple, each element is a np.array

`            RV_per = mlp.Gls([(fit.fit_results.rv_model.jd, fit.fit_results.rv_model.rvs, fit.fit_results.rv_model.rv_err)], fast=True,  verbose=False, ofac=self.gls_ofac.value(), fbeg=omega[-1], fend=omega[0], norm='dlnL') `

Returns this:

 File "es_gui.py", line 2699, in mlp_search
    RV_per = mlp.Gls([(fit.fit_results.rv_model.jd, fit.fit_results.rv_model.rvs, fit.fit_results.rv_model.rv_err)], fast=True,  verbose=False, ofac=self.gls_ofac.value(), fbeg=omega[-1], fend=omega[0], norm='dlnL')
  File "./lib/mlp.py", line 162, in __init__
    self._calcPeriodogram()
  File "./lib/mlp.py", line 286, in _calcPeriodogram
    a0 = map(np.mean, self.y) + map(np.std, self.y)
TypeError: unsupported operand type(s) for +: 'map' and 'map'

**Comment by mzechmeister** [comment]
Yeah, it's very annoying that `map` became an iterator in python 3.

**Comment by mzechmeister** [comment]
The workaround was:
https://github.com/mzechmeister/python/blob/c6faa4b20e4de5f2a652b598ba46fabcb4eb4313/mlp.py#L41-L46
